{{- range .Values.storageClasses }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name }}
provisioner: efs.csi.aws.com
{{- with .mountOptions }}
mountOptions: 
{{ toYaml . }}
{{- end }}
{{- if .reclaimPolicy }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- end }}
{{- with .parameters }}
parameters:
{{ toYaml . | indent 2 }}
{{- end }}
---
{{- end }}
