# Default values for aws-efs-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: amazon/aws-efs-csi-driver
  tag: "v1.2.0"
  pullPolicy: IfNotPresent

sidecars:
  livenessProbeImage:
    repository: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe
    tag: v2.1.0-eks-1-18-1
  nodeDriverRegistrarImage:
    repository: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar
    tag: v2.0.1-eks-1-18-1
  csiProvisionerImage:
    repository: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner
    tag: v2.0.3-eks-1-18-1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

EFSPlugin:
  # -- Resource requests and limits for the efs-plugin container in both the Deployment and DaemonSet
  resources: {}

CSIProvisioner:
  # -- Resource requests and limits for the csi-provisioner container the Deployment
  resources: {}

livenessProbe:
  # -- Resource requests and limits for the liveness-probe container in both the Deployment and DaemonSet
  resources: {}

nodeRegistrar:
  # -- Resource requests and limits for the csi-driver-registrar container the DaemonSet
  resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

node:
  podAnnotations: {}
  tolerations: []

logLevel: 5

hostAliases:
  {}
  # for cross VPC EFS, you need to poison or overwrite the DNS for the efs volume as per
  # https://docs.aws.amazon.com/efs/latest/ug/efs-different-vpc.html#wt6-efs-utils-step3
  # implementing the suggested solution found here:
  # https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/240#issuecomment-676849346
  # EFS Vol ID, IP, Region
  # "fs-01234567":
  #   ip: 10.10.2.2
  #   region: us-east-2

dnsPolicy: ""
dnsConfig:
  {}
  # Example config which uses the AWS nameservers
  # dnsPolicy: "None"
  # dnsConfig:
  #   nameservers:
  #     - 169.254.169.253

serviceAccount:
  controller:
    # Specifies whether a service account should be created
    create: true
    annotations: {}
    ## Enable if EKS IAM for SA is used
    #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/efs-csi-role
    name: efs-csi-controller-sa

controller:
  create: true

storageClasses: []
# Add StorageClass resources like:
# - name: efs-sc
#   mountOptions:
#   - tls
#   parameters:
#     provisioningMode: efs-ap
#     fileSystemId: fs-92107410
#     directoryPerms: "700"
#     gidRangeStart: "1000"
#     gidRangeEnd: "2000"
#     basePath: "/dynamic_provisioning"
